name: Run Cucumber Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install ChromeDriver
        run: |
         sudo apt-get update
         sudo apt-get install -y xvfb lxvfb libxi6 libgbm-dev libxss1 libgtk-3-0 libnss3

      - name: Build and Run Tests
        run: |
           xvfb-run --auto-servernum mvn clean test
      - name: Publish JSON to Dashboard
        run: |
          curl -X POST  https://c6d4-2401-4900-1cb4-b8fd-a822-dcba-bfbb-3675.ngrok-free.app/api/executions \
            -H "Content-Type: application/json" \
            --data "@target/cucumber.json"
